import { Account, SalesTeam, Product, Deal } from './types';

export const sampleAccounts: Account[] = [
  { account: "Acme Corporation", sector: "technolgy", year_established: 1996, revenue: 1100.04, employees: 2822, office_location: "United States", subsidiary_of: "" },
  { account: "Betasoloin", sector: "medical", year_established: 1999, revenue: 251.41, employees: 495, office_location: "United States", subsidiary_of: "" },
  { account: "Betatech", sector: "medical", year_established: 1986, revenue: 647.18, employees: 1185, office_location: "Kenya", subsidiary_of: "" },
  { account: "Bioholding", sector: "medical", year_established: 2012, revenue: 587.34, employees: 1356, office_location: "Philipines", subsidiary_of: "" },
  { account: "Bioplex", sector: "medical", year_established: 1991, revenue: 326.82, employees: 1016, office_location: "United States", subsidiary_of: "" },
  { account: "Blackzim", sector: "retail", year_established: 2009, revenue: 497.11, employees: 1588, office_location: "United States", subsidiary_of: "" },
  { account: "Bluth Company", sector: "technolgy", year_established: 1993, revenue: 1242.32, employees: 3027, office_location: "United States", subsidiary_of: "Acme Corporation" },
  { account: "Bubba Gump", sector: "software", year_established: 2002, revenue: 987.39, employees: 2253, office_location: "United States", subsidiary_of: "" },
  { account: "Cancity", sector: "retail", year_established: 2001, revenue: 718.62, employees: 2448, office_location: "United States", subsidiary_of: "" },
  { account: "Cheers", sector: "entertainment", year_established: 1993, revenue: 4269.9, employees: 6472, office_location: "United States", subsidiary_of: "Massive Dynamic" },
  { account: "Codehow", sector: "software", year_established: 1998, revenue: 2714.9, employees: 2641, office_location: "United States", subsidiary_of: "Acme Corporation" },
  { account: "Condax", sector: "medical", year_established: 2017, revenue: 4.54, employees: 9, office_location: "United States", subsidiary_of: "" },
  { account: "Conecom", sector: "technolgy", year_established: 2005, revenue: 1520.66, employees: 1806, office_location: "United States", subsidiary_of: "" },
  { account: "Dalttechnology", sector: "software", year_established: 2013, revenue: 98.79, employees: 96, office_location: "United States", subsidiary_of: "Bubba Gump" },
  { account: "dambase", sector: "marketing", year_established: 1995, revenue: 2173.98, employees: 2928, office_location: "United States", subsidiary_of: "Inity" },
  { account: "Domzoom", sector: "entertainment", year_established: 1998, revenue: 217.87, employees: 551, office_location: "United States", subsidiary_of: "" },
  { account: "Doncon", sector: "technolgy", year_established: 2010, revenue: 587.72, employees: 1501, office_location: "United States", subsidiary_of: "" },
  { account: "Donquadtech", sector: "technolgy", year_established: 1992, revenue: 1712.68, employees: 3194, office_location: "United States", subsidiary_of: "Acme Corporation" },
  { account: "Dontechi", sector: "software", year_established: 1982, revenue: 4618, employees: 10083, office_location: "United States", subsidiary_of: "" },
  { account: "Donware", sector: "marketing", year_established: 1999, revenue: 1197.44, employees: 2570, office_location: "United States", subsidiary_of: "" },
  { account: "Fasehatice", sector: "retail", year_established: 1990, revenue: 4968.91, employees: 7523, office_location: "United States", subsidiary_of: "" },
  { account: "Faxquote", sector: "telecommunications", year_established: 1995, revenue: 1825.82, employees: 5595, office_location: "United States", subsidiary_of: "Sonron" },
  { account: "Finhigh", sector: "finance", year_established: 2006, revenue: 1102.43, employees: 1759, office_location: "United States", subsidiary_of: "" },
  { account: "Finjob", sector: "employment", year_established: 1988, revenue: 2059.9, employees: 3644, office_location: "United States", subsidiary_of: "" },
  { account: "Funholding", sector: "finance", year_established: 1991, revenue: 2819.5, employees: 7227, office_location: "United States", subsidiary_of: "Golddex" },
  { account: "Ganjaflex", sector: "retail", year_established: 1995, revenue: 5158.71, employees: 17479, office_location: "Japan", subsidiary_of: "" },
  { account: "Gekko & Co", sector: "retail", year_established: 1990, revenue: 2520.83, employees: 3502, office_location: "United States", subsidiary_of: "" },
  { account: "Genco Pura Olive Oil Company", sector: "retail", year_established: 2007, revenue: 894.33, employees: 1635, office_location: "Italy", subsidiary_of: "" },
  { account: "Globex Corporation", sector: "technolgy", year_established: 2000, revenue: 1223.72, employees: 2497, office_location: "Norway", subsidiary_of: "" },
  { account: "Gogozoom", sector: "telecommunications", year_established: 2007, revenue: 86.68, employees: 187, office_location: "United States", subsidiary_of: "Sonron" },
  { account: "Golddex", sector: "finance", year_established: 2008, revenue: 52.5, employees: 165, office_location: "United States", subsidiary_of: "" },
  { account: "Goodsilron", sector: "marketing", year_established: 2000, revenue: 2952.73, employees: 5107, office_location: "United States", subsidiary_of: "" },
  { account: "Green-Plus", sector: "services", year_established: 2003, revenue: 692.19, employees: 1922, office_location: "United States", subsidiary_of: "" },
  { account: "Groovestreet", sector: "retail", year_established: 2003, revenue: 223.8, employees: 299, office_location: "United States", subsidiary_of: "" },
  { account: "Hatfan", sector: "services", year_established: 1982, revenue: 792.46, employees: 1299, office_location: "United States", subsidiary_of: "" },
  { account: "Hottechi", sector: "technolgy", year_established: 1997, revenue: 8170.38, employees: 16499, office_location: "Korea", subsidiary_of: "" },
  { account: "Initech", sector: "telecommunications", year_established: 1994, revenue: 6395.05, employees: 20275, office_location: "United States", subsidiary_of: "" },
  { account: "Inity", sector: "marketing", year_established: 1986, revenue: 2403.58, employees: 8801, office_location: "United States", subsidiary_of: "" },
  { account: "Isdom", sector: "medical", year_established: 2002, revenue: 3178.24, employees: 4540, office_location: "United States", subsidiary_of: "" },
  { account: "Iselectrics", sector: "technolgy", year_established: 2011, revenue: 527.11, employees: 1428, office_location: "United States", subsidiary_of: "Acme Corporation" },
];

export const sampleSalesTeams: SalesTeam[] = [
  { sales_agent: "Anna Snelling", manager: "Dustin Brinkmann", regional_office: "Central" },
  { sales_agent: "Cecily Lampkin", manager: "Dustin Brinkmann", regional_office: "Central" },
  { sales_agent: "Versie Hillebrand", manager: "Dustin Brinkmann", regional_office: "Central" },
  { sales_agent: "Lajuana Vencill", manager: "Dustin Brinkmann", regional_office: "Central" },
  { sales_agent: "Moses Frase", manager: "Dustin Brinkmann", regional_office: "Central" },
  { sales_agent: "Jonathan Berthelot", manager: "Melvin Marxen", regional_office: "Central" },
  { sales_agent: "Marty Freudenburg", manager: "Melvin Marxen", regional_office: "Central" },
  { sales_agent: "Gladys Colclough", manager: "Melvin Marxen", regional_office: "Central" },
  { sales_agent: "Niesha Huffines", manager: "Melvin Marxen", regional_office: "Central" },
  { sales_agent: "Darcel Schlecht", manager: "Melvin Marxen", regional_office: "Central" },
  { sales_agent: "Violet Mclelland", manager: "Cara Losch", regional_office: "East" },
  { sales_agent: "Corliss Cosme", manager: "Cara Losch", regional_office: "East" },
  { sales_agent: "Rosie Papadopoulos", manager: "Cara Losch", regional_office: "East" },
  { sales_agent: "Garret Kinder", manager: "Cara Losch", regional_office: "East" },
  { sales_agent: "Wilburn Farren", manager: "Cara Losch", regional_office: "East" },
  { sales_agent: "Daniell Hammack", manager: "Rocco Neubert", regional_office: "East" },
  { sales_agent: "Cassey Cress", manager: "Rocco Neubert", regional_office: "East" },
  { sales_agent: "Donn Cantrell", manager: "Rocco Neubert", regional_office: "East" },
  { sales_agent: "Reed Clapper", manager: "Rocco Neubert", regional_office: "East" },
  { sales_agent: "Boris Faz", manager: "Rocco Neubert", regional_office: "East" },
  { sales_agent: "Vicki Laflamme", manager: "Celia Rouche", regional_office: "West" },
  { sales_agent: "Rosalina Dieter", manager: "Celia Rouche", regional_office: "West" },
  { sales_agent: "Hayden Neloms", manager: "Celia Rouche", regional_office: "West" },
  { sales_agent: "Markita Hansen", manager: "Celia Rouche", regional_office: "West" },
  { sales_agent: "Elease Gluck", manager: "Celia Rouche", regional_office: "West" },
  { sales_agent: "James Ascencio", manager: "Summer Sewald", regional_office: "West" },
  { sales_agent: "Kary Hendrixson", manager: "Summer Sewald", regional_office: "West" },
  { sales_agent: "Kami Bicknell", manager: "Summer Sewald", regional_office: "West" },
  { sales_agent: "Zane Levy", manager: "Summer Sewald", regional_office: "West" },
  { sales_agent: "Maureen Marcano", manager: "Summer Sewald", regional_office: "West" },
];

export const sampleProducts: Product[] = [
  { product: "GTX Basic", series: "GTX", sales_price: 550 },
  { product: "GTX Pro", series: "GTX", sales_price: 4821 },
  { product: "MG Special", series: "MG", sales_price: 55 },
  { product: "MG Advanced", series: "MG", sales_price: 3393 },
  { product: "GTX Plus Pro", series: "GTX", sales_price: 5482 },
  { product: "GTX Plus Basic", series: "GTX", sales_price: 1096 },
  { product: "GTK 500", series: "GTK", sales_price: 26768 },
];

export const samplePipeline: Deal[] = [
  { opportunity_id: "1C1I7A6R", sales_agent: "Moses Frase", product: "GTX Plus Basic", account: "Cancity", deal_stage: "Won", engage_date: "2016-10-20", close_date: "2017-03-01", close_value: 1054 },
  { opportunity_id: "Z063OYW0", sales_agent: "Darcel Schlecht", product: "GTX Pro", account: "Isdom", deal_stage: "Won", engage_date: "2016-10-25", close_date: "2017-03-11", close_value: 4514 },
  { opportunity_id: "EC4QE1BX", sales_agent: "Darcel Schlecht", product: "MG Special", account: "Cancity", deal_stage: "Won", engage_date: "2016-10-25", close_date: "2017-03-07", close_value: 50 },
  { opportunity_id: "MV1LWRNH", sales_agent: "Moses Frase", product: "GTX Basic", account: "Codehow", deal_stage: "Won", engage_date: "2016-10-25", close_date: "2017-03-09", close_value: 588 },
  { opportunity_id: "PE84CX4O", sales_agent: "Zane Levy", product: "GTX Basic", account: "Hatfan", deal_stage: "Won", engage_date: "2016-10-25", close_date: "2017-03-02", close_value: 517 },
  { opportunity_id: "ZNBS69V1", sales_agent: "Anna Snelling", product: "MG Special", account: "Ron-tech", deal_stage: "Won", engage_date: "2016-10-29", close_date: "2017-03-01", close_value: 49 },
  { opportunity_id: "9ME3374G", sales_agent: "Vicki Laflamme", product: "MG Special", account: "J-Texon", deal_stage: "Won", engage_date: "2016-10-30", close_date: "2017-03-02", close_value: 57 },
  { opportunity_id: "7GN8Q4LL", sales_agent: "Markita Hansen", product: "GTX Basic", account: "Cheers", deal_stage: "Won", engage_date: "2016-11-01", close_date: "2017-03-07", close_value: 601 },
  { opportunity_id: "OLK9LKZB", sales_agent: "Niesha Huffines", product: "GTX Plus Basic", account: "Zumgoity", deal_stage: "Won", engage_date: "2016-11-01", close_date: "2017-03-03", close_value: 1026 },
  { opportunity_id: "HAXMC4IX", sales_agent: "James Ascencio", product: "MG Advanced", account: "", deal_stage: "Engaging", engage_date: "2016-11-03", close_date: "", close_value: 0 },
  { opportunity_id: "NL3JZH1Z", sales_agent: "Anna Snelling", product: "MG Special", account: "Bioholding", deal_stage: "Won", engage_date: "2016-11-04", close_date: "2017-03-10", close_value: 53 },
  { opportunity_id: "KWVA7VR1", sales_agent: "Gladys Colclough", product: "GTX Pro", account: "Genco Pura Olive Oil Company", deal_stage: "Lost", engage_date: "2016-11-04", close_date: "2017-03-18", close_value: 0 },
  { opportunity_id: "S8DX3XOU", sales_agent: "James Ascencio", product: "GTX Plus Pro", account: "Sunnamplex", deal_stage: "Won", engage_date: "2016-11-04", close_date: "2017-03-10", close_value: 5169 },
  { opportunity_id: "ENB2XD8G", sales_agent: "Maureen Marcano", product: "GTX Plus Pro", account: "Sonron", deal_stage: "Won", engage_date: "2016-11-04", close_date: "2017-03-06", close_value: 4631 },
  { opportunity_id: "09YE9QOV", sales_agent: "Hayden Neloms", product: "MG Advanced", account: "Finjob", deal_stage: "Won", engage_date: "2016-11-05", close_date: "2017-03-11", close_value: 3393 },
  { opportunity_id: "3F5MZNEH", sales_agent: "Rosalina Dieter", product: "MG Special", account: "Sonron", deal_stage: "Lost", engage_date: "2016-11-05", close_date: "2017-03-03", close_value: 0 },
  { opportunity_id: "M6WEJXC0", sales_agent: "Rosalina Dieter", product: "MG Advanced", account: "Scotfind", deal_stage: "Won", engage_date: "2016-11-05", close_date: "2017-03-06", close_value: 3284 },
  { opportunity_id: "6PTR7VBR", sales_agent: "Versie Hillebrand", product: "MG Special", account: "Treequote", deal_stage: "Won", engage_date: "2016-11-06", close_date: "2017-03-05", close_value: 61 },
  { opportunity_id: "902REDPA", sales_agent: "Daniell Hammack", product: "GTX Pro", account: "Xx-zobam", deal_stage: "Lost", engage_date: "2016-11-07", close_date: "2017-03-09", close_value: 0 },
  { opportunity_id: "5J9CMGDV", sales_agent: "Elease Gluck", product: "MG Special", account: "Rantouch", deal_stage: "Won", engage_date: "2016-11-07", close_date: "2017-03-08", close_value: 46 },
  { opportunity_id: "JJXRR8R6", sales_agent: "James Ascencio", product: "GTX Plus Pro", account: "Fasehatice", deal_stage: "Lost", engage_date: "2016-11-07", close_date: "2017-03-17", close_value: 0 },
  { opportunity_id: "WF4HA5NW", sales_agent: "Moses Frase", product: "MG Special", account: "Ron-tech", deal_stage: "Won", engage_date: "2016-11-07", close_date: "2017-03-18", close_value: 50 },
  { opportunity_id: "C5K2JP1H", sales_agent: "Violet Mclelland", product: "GTX Plus Basic", account: "Vehement Capital Partners", deal_stage: "Won", engage_date: "2016-11-07", close_date: "2017-03-11", close_value: 1014 },
  { opportunity_id: "ADRB8OMB", sales_agent: "Darcel Schlecht", product: "GTX Basic", account: "Warephase", deal_stage: "Won", engage_date: "2016-11-08", close_date: "2017-03-26", close_value: 561 },
  { opportunity_id: "SBCR987L", sales_agent: "Kami Bicknell", product: "GTX Basic", account: "Zoomit", deal_stage: "Won", engage_date: "2016-11-10", close_date: "2017-03-23", close_value: 590 },
  { opportunity_id: "UP409DSB", sales_agent: "Maureen Marcano", product: "MG Advanced", account: "Ganjaflex", deal_stage: "Engaging", engage_date: "2016-11-10", close_date: "", close_value: 0 },
  { opportunity_id: "JSD4APT2", sales_agent: "Versie Hillebrand", product: "MG Special", account: "Bioholding", deal_stage: "Won", engage_date: "2016-11-10", close_date: "2017-03-12", close_value: 61 },
  { opportunity_id: "AO9Z2D17", sales_agent: "Violet Mclelland", product: "GTX Plus Pro", account: "Xx-zobam", deal_stage: "Lost", engage_date: "2016-11-10", close_date: "2017-03-11", close_value: 0 },
  { opportunity_id: "5M58DTJK", sales_agent: "Elease Gluck", product: "MG Special", account: "Cheers", deal_stage: "Won", engage_date: "2016-11-11", close_date: "2017-03-05", close_value: 58 },
  { opportunity_id: "KNY1OSAB", sales_agent: "Maureen Marcano", product: "GTX Pro", account: "Labdrill", deal_stage: "Won", engage_date: "2016-11-11", close_date: "2017-03-14", close_value: 4899 },
  { opportunity_id: "EAZDUUM9", sales_agent: "Rosie Papadopoulos", product: "MG Advanced", account: "Zotware", deal_stage: "Lost", engage_date: "2016-11-11", close_date: "2017-03-01", close_value: 0 },
  { opportunity_id: "2STUSOFE", sales_agent: "Versie Hillebrand", product: "MG Special", account: "dambase", deal_stage: "Won", engage_date: "2016-11-11", close_date: "2017-03-03", close_value: 67 },
  { opportunity_id: "JYKM0B00", sales_agent: "James Ascencio", product: "GTX Pro", account: "Xx-holding", deal_stage: "Won", engage_date: "2016-11-12", close_date: "2017-03-06", close_value: 4338 },
  { opportunity_id: "KU28360J", sales_agent: "Kary Hendrixson", product: "GTX Basic", account: "Fasehatice", deal_stage: "Won", engage_date: "2016-11-12", close_date: "2017-03-19", close_value: 578 },
  { opportunity_id: "N4SD17JR", sales_agent: "Reed Clapper", product: "GTX Basic", account: "Acme Corporation", deal_stage: "Won", engage_date: "2016-11-12", close_date: "2017-03-01", close_value: 556 },
  { opportunity_id: "E67P9Y3Q", sales_agent: "Rosalina Dieter", product: "GTX Basic", account: "Green-Plus", deal_stage: "Won", engage_date: "2016-11-12", close_date: "2017-03-03", close_value: 635 },
  { opportunity_id: "AT3MMVIS", sales_agent: "Wilburn Farren", product: "MG Advanced", account: "The New York Inquirer", deal_stage: "Won", engage_date: "2016-11-12", close_date: "2017-03-07", close_value: 3045 },
  { opportunity_id: "REJ11LRY", sales_agent: "Garret Kinder", product: "GTX Plus Basic", account: "Mathtouch", deal_stage: "Won", engage_date: "2016-11-13", close_date: "2017-03-14", close_value: 1233 },
  { opportunity_id: "ERV0CAZ7", sales_agent: "Versie Hillebrand", product: "MG Special", account: "Zumgoity", deal_stage: "Won", engage_date: "2016-11-13", close_date: "2017-03-09", close_value: 60 },
  { opportunity_id: "8SOQADK7", sales_agent: "Anna Snelling", product: "MG Special", account: "Gogozoom", deal_stage: "Lost", engage_date: "2016-11-14", close_date: "2017-03-30", close_value: 0 },
  { opportunity_id: "TCHFT25B", sales_agent: "Darcel Schlecht", product: "GTX Basic", account: "Stanredtax", deal_stage: "Lost", engage_date: "2016-11-14", close_date: "2017-03-08", close_value: 0 },
  { opportunity_id: "CZVN09WN", sales_agent: "Darcel Schlecht", product: "GTX Plus Basic", account: "Konmatfix", deal_stage: "Won", engage_date: "2016-11-14", close_date: "2017-03-20", close_value: 1170 },
  { opportunity_id: "EG7OFLFR", sales_agent: "Kami Bicknell", product: "GTX Basic", account: "", deal_stage: "Engaging", engage_date: "2016-11-14", close_date: "", close_value: 0 },
  { opportunity_id: "30UQWUKB", sales_agent: "Marty Freudenburg", product: "GTX Plus Basic", account: "Genco Pura Olive Oil Company", deal_stage: "Won", engage_date: "2016-11-15", close_date: "2017-03-20", close_value: 1162 },
  { opportunity_id: "OLVI7L8M", sales_agent: "Cassey Cress", product: "GTX Pro", account: "", deal_stage: "Engaging", engage_date: "2016-11-16", close_date: "", close_value: 0 },
  { opportunity_id: "97UN20YY", sales_agent: "Darcel Schlecht", product: "MG Advanced", account: "Conecom", deal_stage: "Won", engage_date: "2016-11-16", close_date: "2017-03-14", close_value: 3725 },
  { opportunity_id: "JXLERZ9O", sales_agent: "Kary Hendrixson", product: "GTX Basic", account: "Golddex", deal_stage: "Won", engage_date: "2016-11-16", close_date: "2017-03-31", close_value: 559 },
  { opportunity_id: "6ROE69W5", sales_agent: "Rosalina Dieter", product: "GTX Basic", account: "Plexzap", deal_stage: "Lost", engage_date: "2016-11-16", close_date: "2017-03-11", close_value: 0 },
  { opportunity_id: "0DFXFKT7", sales_agent: "Darcel Schlecht", product: "GTX Plus Basic", account: "Rundofase", deal_stage: "Lost", engage_date: "2016-11-17", close_date: "2017-03-21", close_value: 0 },
  { opportunity_id: "XKMZVSN4", sales_agent: "James Ascencio", product: "GTX Plus Pro", account: "Sonron", deal_stage: "Won", engage_date: "2016-11-17", close_date: "2017-03-05", close_value: 4667 },
  { opportunity_id: "IU8V0BZK", sales_agent: "Marty Freudenburg", product: "GTX Plus Basic", account: "Finhigh", deal_stage: "Won", engage_date: "2016-11-17", close_date: "2017-03-17", close_value: 903 },
  { opportunity_id: "XY42936P", sales_agent: "Maureen Marcano", product: "GTX Plus Basic", account: "Finjob", deal_stage: "Won", engage_date: "2016-11-17", close_date: "2017-03-13", close_value: 1180 },
  { opportunity_id: "XRN54MBM", sales_agent: "Niesha Huffines", product: "GTX Basic", account: "Ron-tech", deal_stage: "Won", engage_date: "2016-11-17", close_date: "2017-03-05", close_value: 487 },
  { opportunity_id: "2V848WZD", sales_agent: "Lajuana Vencill", product: "MG Advanced", account: "Stanredtax", deal_stage: "Won", engage_date: "2016-11-18", close_date: "2017-03-04", close_value: 3180 },
  { opportunity_id: "ONYNTUCG", sales_agent: "Darcel Schlecht", product: "GTX Pro", account: "Funholding", deal_stage: "Lost", engage_date: "2016-11-19", close_date: "2017-03-17", close_value: 0 },
  { opportunity_id: "HIOHX80Y", sales_agent: "Darcel Schlecht", product: "MG Advanced", account: "Gogozoom", deal_stage: "Won", engage_date: "2016-11-19", close_date: "2017-03-18", close_value: 3563 },
  { opportunity_id: "F5U1ACDD", sales_agent: "Kami Bicknell", product: "GTX Plus Basic", account: "", deal_stage: "Engaging", engage_date: "2016-11-19", close_date: "", close_value: 0 },
  { opportunity_id: "LPKT07PV", sales_agent: "Boris Faz", product: "GTX Pro", account: "Opentech", deal_stage: "Won", engage_date: "2016-11-20", close_date: "2017-03-23", close_value: 4704 },
  { opportunity_id: "WPB2SLIG", sales_agent: "Donn Cantrell", product: "GTX Plus Pro", account: "Silis", deal_stage: "Won", engage_date: "2016-11-20", close_date: "2017-03-14", close_value: 5585 },
  { opportunity_id: "XUSUEAV7", sales_agent: "Elease Gluck", product: "GTK 500", account: "Zoomit", deal_stage: "Won", engage_date: "2016-11-20", close_date: "2017-03-09", close_value: 25897 },
  { opportunity_id: "ZZY4516R", sales_agent: "Hayden Neloms", product: "MG Advanced", account: "", deal_stage: "Engaging", engage_date: "2016-11-20", close_date: "", close_value: 0 },
  { opportunity_id: "3TYPII47", sales_agent: "Kami Bicknell", product: "GTX Plus Basic", account: "Goodsilron", deal_stage: "Won", engage_date: "2016-11-20", close_date: "2017-03-03", close_value: 1207 },
  { opportunity_id: "7WAX8Z8O", sales_agent: "Lajuana Vencill", product: "MG Advanced", account: "Cancity", deal_stage: "Lost", engage_date: "2016-11-20", close_date: "2017-03-08", close_value: 0 },
  { opportunity_id: "MYDUMR3R", sales_agent: "Lajuana Vencill", product: "GTX Basic", account: "Rangreen", deal_stage: "Won", engage_date: "2016-11-20", close_date: "2017-03-04", close_value: 559 },
  { opportunity_id: "0DRC1U9Q", sales_agent: "Maureen Marcano", product: "GTX Basic", account: "Green-Plus", deal_stage: "Engaging", engage_date: "2016-11-20", close_date: "", close_value: 0 },
  { opportunity_id: "37JFKD4I", sales_agent: "Niesha Huffines", product: "GTX Plus Basic", account: "dambase", deal_stage: "Won", engage_date: "2016-11-20", close_date: "2017-03-09", close_value: 1033 },
  { opportunity_id: "25YKPHX8", sales_agent: "Donn Cantrell", product: "GTX Basic", account: "Kan-code", deal_stage: "Won", engage_date: "2016-11-21", close_date: "2017-03-21", close_value: 462 },
  { opportunity_id: "BXXMA7F3", sales_agent: "Hayden Neloms", product: "MG Advanced", account: "Nam-zim", deal_stage: "Lost", engage_date: "2016-11-21", close_date: "2017-03-01", close_value: 0 },
  { opportunity_id: "GIUUTBXM", sales_agent: "Kary Hendrixson", product: "GTX Pro", account: "Y-corporation", deal_stage: "Won", engage_date: "2016-11-21", close_date: "2017-03-14", close_value: 5539 },
  { opportunity_id: "MFX2LR1Q", sales_agent: "Lajuana Vencill", product: "MG Advanced", account: "Ron-tech", deal_stage: "Won", engage_date: "2016-11-21", close_date: "2017-03-15", close_value: 3573 },
  { opportunity_id: "DUHE9FLY", sales_agent: "Marty Freudenburg", product: "GTX Pro", account: "Conecom", deal_stage: "Won", engage_date: "2016-11-21", close_date: "2017-03-01", close_value: 4926 },
  { opportunity_id: "96BSG7R1", sales_agent: "Zane Levy", product: "GTX Plus Basic", account: "Sunnamplex", deal_stage: "Lost", engage_date: "2016-11-21", close_date: "2017-03-17", close_value: 0 },
  { opportunity_id: "7FQMSWIX", sales_agent: "Corliss Cosme", product: "MG Special", account: "Bioplex", deal_stage: "Won", engage_date: "2016-11-22", close_date: "2017-03-04", close_value: 62 },
  { opportunity_id: "C20AVXN7", sales_agent: "Darcel Schlecht", product: "GTX Pro", account: "Gogozoom", deal_stage: "Won", engage_date: "2016-11-22", close_date: "2017-03-14", close_value: 4359 },
  { opportunity_id: "GS1QVWCR", sales_agent: "Kami Bicknell", product: "GTX Basic", account: "Plusstrip", deal_stage: "Won", engage_date: "2016-11-22", close_date: "2017-03-31", close_value: 566 },
  { opportunity_id: "ZWH8FXY3", sales_agent: "Marty Freudenburg", product: "GTX Basic", account: "Toughzap", deal_stage: "Won", engage_date: "2016-11-22", close_date: "2017-03-03", close_value: 508 },
  { opportunity_id: "2U94Y3Q9", sales_agent: "Rosie Papadopoulos", product: "MG Advanced", account: "Vehement Capital Partners", deal_stage: "Lost", engage_date: "2016-11-22", close_date: "2017-03-20", close_value: 0 },
  { opportunity_id: "AAR79NOO", sales_agent: "Versie Hillebrand", product: "MG Special", account: "Codehow", deal_stage: "Won", engage_date: "2016-11-22", close_date: "2017-03-11", close_value: 51 },
  { opportunity_id: "B6B0PNR2", sales_agent: "Vicki Laflamme", product: "GTX Pro", account: "Dalttechnology", deal_stage: "Won", engage_date: "2016-11-22", close_date: "2017-03-05", close_value: 4899 },
];
